name: Amplify Custom Pipeline - main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: Deploy backend with Amplify
        run: |
          export CI=1
          npx ampx pipeline-deploy \
            --branch main \
            --app-id d1wf6ee49outtl
      
      - name: Trigger frontend build
        if: success()
        run: |
          # Trigger Amplify Console frontend build via webhook
          curl -X POST 'https://webhooks.amplify.eu-north-1.amazonaws.com/prod/webhooks?id=6273f8ae-0b39-4065-b587-ed5cb468cc15&token=euGsQiUrNHKWUeQIIqVq1h98tzXivhCmREwOqLFag'
